// <auto-generated />
using System;
using Medical.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Medical.Migrations
{
    [DbContext(typeof(MedicalContext))]
    [Migration("20260120125011_ClearHardcodedStepsConfig")]
    partial class ClearHardcodedStepsConfig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Medical.Models.ViewPublicForm", b =>
                {
                    b.Property<Guid>("ViewPublicFormId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdditionalFieldsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FieldLabelsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormDataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormSchemaJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FormVersion")
                        .HasColumnType("int");

                    b.Property<bool>("IsConfig")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("ViewPublicFormId");

                    b.ToTable("ViewPublicForm");
                });
#pragma warning restore 612, 618
        }
    }
}
